version: '3.8'
services:
    umerx_blackdog_configurator_backend:
        build:
            context: ./.devcontainer
            dockerfile: Dockerfile
        command: sleep infinity
        volumes:
            - ./:/workspace
    adminer:
        image: adminer
        depends_on:
            - db
        restart: always
        ports:
            - ${BLACKDOG_CONFIGURATOR_BACKEND_ADMINER_HOST_PORT}:8080
networks:
    default:
        external: true
        name: 'umerx_blackdog'
