name: Build
on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:
concurrency: ${{ github.ref_name }}
jobs:
    deploy:
        name: Deploy
        runs-on: [self-hosted, linux, ARM64]
        permissions:
            contents: read
            packages: write
        env:
            DOCKER_IMAGE_REPO: ${{ github.repository }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - # Add support for more platforms with QEMU (optional)
              # https://github.com/docker/setup-qemu-action
              name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                  platforms: all
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Downcase DOCKER_IMAGE_REPO
              run: |
                  echo "DOCKER_IMAGE_REPO=${DOCKER_IMAGE_REPO,,}" >>${GITHUB_ENV};
            - name: Generate Docker image tags
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: |
                      ghcr.io/${{ env.DOCKER_IMAGE_REPO }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=tag
                      type=sha
                      type=semver,pattern={{major}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}.{{minor}}.{{patch}}
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  platforms: linux/arm64
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
